from legacy.aurora_tms_mvp import (
    STATUS_CAMINHAO_DISPONIVEL,
    STATUS_CAMINHAO_EM_ROTA,
    STATUS_CAMINHAO_MANUTENCAO,
    STATUS_MOTORISTA_DISPONIVEL,
    STATUS_MOTORISTA_EM_VIAGEM,
    STATUS_MOTORISTA_AFASTADO,
    STATUS_CARGA_PATIO,
    STATUS_CARGA_RESERVADA,
    STATUS_CARGA_EMBARCADA,
    STATUS_CARGA_ENTREGUE,
    STATUS_CARGA_CANCELADA,
    STATUS_VIAGEM_PLANEJADA,
    STATUS_VIAGEM_EM_ANDAMENTO,
    STATUS_VIAGEM_FINALIZADA,
    STATUS_VIAGEM_CANCELADA,
    TIPO_EVENTO_CADASTRO,
    TIPO_EVENTO_ATUALIZACAO,
    TIPO_EVENTO_OPERACAO,
    TIPO_EVENTO_RELATORIO,
    TIPO_EVENTO_ALERTA,
)

__all__ = [name for name in globals() if name.isupper()]
